services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: supplies
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mysql_data:
  mongodb_data:
